Add INCLUDE command to include other Pifiles easily in our script without using sh'isms.
Nature40/pimod pull request #33
Opened 2021-08-28 04:31 UTC by aniongithub

To include other Pifiles, it's easy to use the `source` command, but this detracts from the Dockerfile-like nature of pimod. The `INCLUDE` command lets us do this, while ensuring that only Pifiles can be included (it appends a `.Pifile` to the provided filename).

2021-08-28 08:07 UTC, oxzi commented
Thank you very much for your contribution! I like the idea of a more native feeling way to extend or include other Pifiles.

However, with your current approach, all `INCLUDE`d files will only be sourced in the `10-setup` stage, as in every other stage the `INCLUDE` function does nothing. This results in the included Pifile being only sourced once, with only the `10-setup` functions being available.

The current stage logic is implemented in a very straight forward way with a code block like the following for each of the four stages:
https://github.com/Nature40/pimod/blob/a75017b8e038ff2a35279c620f2dd1ad6ad0a1e0/modules/pifile.sh#L36-L43
Thus, only the stage's commands have an implementation during the stage.

As one wants to extend another Pifile with all its stages, your `INCLUDE` command should be available for all of those. The most easy way would be to implement its function only within the `00-commands.sh` file, as it is sourced first for every stage.

Would you please also add a brief description of the command to the `README.md`?

Thanks again!

2021-08-31 18:08 UTC, aniongithub commented
Incorporated the suggested changes. Thanks!

2021-09-20 12:30 UTC, oxzi requested changes
Thanks again and please excuse the delay. I accidentally overlooked your updates to this PR.

Would you please work on my two last suggestions as I would like to merge your changes.

2021-09-20 12:30 UTC, oxzi commented on stages/00-commands.sh
> +  filename="${$1%.*}"
There is a typo in the substitution resulting in an error.

```suggestion
  filename="${1%.*}"
```

2021-09-20 12:30 UTC, oxzi commented on stages/00-commands.sh
> +}
Pardon, this might be very nitpicking. But would you please move the function up in this file before the comment for the _Stage 1x_ section, as it is available in all stages?

2021-09-22 22:14 UTC, aniongithub commented on stages/00-commands.sh
> +}
No worries, can do!

2021-09-22 22:16 UTC, aniongithub commented
Done, updated according to suggestions!

2021-09-23 18:14 UTC, oxzi approved these changes
LGTM, thanks again :)

2021-09-23 18:15 UTC, oxzi commented
The one CI error appears due to the unavailability of `INCLUDE` on the current `master` branch.

2021-09-23 18:16 UTC, merged