modules: chroot: Add cgroup binds
Nature40/pimod pull request #41
Opened 2021-11-04 14:25 UTC by patrickelectric

Fix #38 

Allow the usage of dockerd on pimod

2021-11-04 16:19 UTC, oxzi requested changes
Thanks for raising this issue and suggesting this fix. Would you please try the suggested change? Btw, this should hopefully also satisfy the CI.

__EDIT:__ Might you please also add this change/fix to the CHANGELOG? Thanks.

2021-11-04 16:19 UTC, oxzi commented on modules/chroot.sh
> +  mount --bind /proc/cgroups "${CHROOT_MOUNT}/proc/cgroups"
This entry shouldn't be necessary, as it should already be covered by the previous bind mount of `/proc`.

2021-11-04 16:19 UTC, oxzi commented on modules/chroot.sh
> +  mount --rbind /sys/fs/cgroup "${CHROOT_MOUNT}/sys/fs/cgroup"
The `--rbind` is a good catch for `/sys`. Maybe you want to change the previous bind mount for `/sys` to an `--rbind` mount?

2021-11-04 16:28 UTC, patrickelectric commented
@oxzi done!

2021-11-04 16:51 UTC, oxzi requested changes

2021-11-04 16:51 UTC, oxzi commented on modules/chroot.sh
> +  mount --rbind /sys "${CHROOT_MOUNT}/sys"
Thanks a lot for your fast changes.

However, now we are bind mounting `/sys` twice, as it was already bind mounted before in line 13. Would you please remove the other, non `--rbind` mount?

2021-11-04 17:06 UTC, oxzi commented
I am not quite sure why the CI is unhappy about the umount, as it works perfectly on my machine. I will try to investigate this one later.

2021-11-05 09:54 UTC, patrickelectric commented
@oxzi It appears to be working fine on CI, I have just tested on my fork.

2021-11-09 10:56 UTC, patrickelectric commented
@oxzi can you check it now ?

2021-11-09 19:43 UTC, oxzi approved these changes
LGTM!

Thanks a lot and please excuse the delay.

2021-11-09 19:43 UTC, merged