make sure the host version of reslov.conf is used in any case
Nature40/pimod pull request #55
Opened 2022-01-18 11:24 UTC by sensslen

With this PR we make sure that the host's resolv.conf is used in any case during chroot. I don't see why the mechanism used to do this differently. In any case: this fixes #54.

2022-01-20 12:06 UTC, sensslen commented
I just found out the hard way that with the changes in this PR no more modifications can be made to the original resolv.conf file (which I need to do unfortunately).

Does anybody know of any possible solutions to this?

2022-01-31 09:32 UTC, oxzi requested changes
Honestly, I am not quite sure how I feel about this PR.

On the one hand, I would guess that using the host's `/etc/resolv.conf` is desired.
This could be achieved easily by bind mounting the host's file into the guest.
However, on the other hand, I am pretty sure there are good reasons to alter the guest's `/etc/resolv.conf` within pimod.

Further, the special case to alter the host's `/etc/rescolv.conf` on the fly, and thereby also the guest's one, can only be realized through bind mounting.
Once again, this prevents changes from the guest.

I hope you see the same dilemma as I do.

As a workaround, you could ensure that no `/etc/resolv.conf` is present within your base image.
Thus, the host's file will always be bind mounted.

I am open for feedback, as the current situation does not seem optimal for me.

2022-01-31 09:32 UTC, oxzi commented on modules/env.sh
> +ENV_VARS["PIMOD"]="true"
I don't see the purpose of this additional `ENV_VAR`. How is this related to the changes?

2022-01-31 14:20 UTC, sensslen commented on modules/env.sh
> +ENV_VARS["PIMOD"]="true"
This environment variable is a very simplistic way of detecting that the image is indeed modified inside of pimod and thus take ecounter measures against trying to modify the wrong configuration file. As you already mentioned. I am also not very happy about the situation but the only real possible resolution I currently see is to switch to spinning up a real qemu instance which in turn makes the guest operation system boot like normal. This would indeed have some drawbacks - most notably it would take quite some time to boot.

2022-02-07 21:30 UTC, closed without merging